name:                zayin
version:             0.1.0.0
github:              "githubuser/zayin"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/zayin#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.12 && < 1
- containers >= 0.6 && < 1
- directory >= 1.3 && < 2
- filepath >= 1.4 && < 2
- file-embed >= 0 && < 1
- mtl >= 2.3 && < 3
- optparse-applicative >= 0.18 && < 1
- process >= 1.6 && < 2
- temporary >= 1.3 && < 2
- text >= 2.1 && < 3
- unordered-containers >= 0.2 && < 1
- parsec >= 3.1 && < 4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  zayin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zayin

tests:
  zayin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zayin
